name: Check code style

on:
    push:
        branches: [ base ]
        paths-ignore:
            - "**.md"
            - "LICENSE.txt"
            - ".idea/**"
            - ".gitignore"
            - ".editorconfig"
    pull_request:
        branches: [ base ]
        paths-ignore:
            - "**.md"
            - "LICENSE.txt"
            - ".idea/**"
            - ".gitignore"
            - ".editorconfig"

jobs:
    code_style:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                ruby-version: [ '3.1', '2.7' ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Ruby ${{ matrix.ruby-version }}
                uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
                with:
                    ruby-version: ${{ matrix.ruby-version }}
                    bundler-cache: true
            -   name: Install dependencies
                run: bundle install
            -   name: Run tests
                run: bundle exec rake standard
