name: Check functionality

on:
    push:
        branches: [ base ]
        paths-ignore:
            - "**.md"
            - "LICENSE.txt"
            - ".idea/**"
    pull_request:
        branches: [ base ]
        paths-ignore:
            - "**.md"
            - "LICENSE.txt"
            - ".idea/**"

concurrency:
    group: ${{ github.head_ref }}-test
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                ruby_version: [ "3.1", "2.7" ]
                appraisal:
                    - jekyll-35
                    - jekyll-36
                    - jekyll-37
                    - jekyll-38
                    - jekyll-39
                    - jekyll-40
                    - jekyll-41
                    - jekyll-42
                    - jekyll-43
                exclude:
                    # exclude incompatible dependency combos
                    -   ruby_version: "3.1"
                        appraisal: jekyll-35
                    -   ruby_version: "3.1"
                        appraisal: jekyll-36
                    -   ruby_version: "3.1"
                        appraisal: jekyll-37
                    -   ruby_version: "3.1"
                        appraisal: jekyll-38
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Ruby ${{ matrix.ruby_version }}
                uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
                with:
                    ruby-version: ${{ matrix.ruby_version }}
            -   name: Update RubyGems version
                # Setting bundle install path causes default rubygems (3.1.6 / 3.3.3) to blows up
                # Jekyll 4.3 causes default rubygems to blow up because of jekyll-sass-converter
                # However, the latest rubygems blows up because of appraisal
                # This is the version that NEITHER appraisal or jekyll-sass-converter
                # blows up from incompatible dependencies
                run: gem update --system 3.3.22 && gem update --system
            -   uses: actions/cache@v3
                # This will save all appraisal patterns
                with:
                    path: vendor/bundle
                    key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
                    restore-keys: |
                        bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby_version }}-
            -   name: Install base dependencies
                # Putting the gems in vendor path allows appraisal to install dependencies there as well
                run: |
                    bundle config path vendor/bundle
                    bundle install
            -   name: Install dependencies for appraisal
                # This creates appraisal-specific Gemfiles
                run: bundle exec appraisal install
            -   name: Run tests
                run: bundle exec appraisal ${{ matrix.appraisal }} rake spec
